"""empty message

Revision ID: 14072d1f3cec
Revises: 4d452b8f4a16
Create Date: 2015-07-19 15:01:16.170000

"""

# revision identifiers, used by Alembic.
revision = '14072d1f3cec'
down_revision = '4d452b8f4a16'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
