"""empty message

Revision ID: 4d452b8f4a16
Revises: e37bc10aebd
Create Date: 2015-07-19 14:42:49.477000

"""

# revision identifiers, used by Alembic.
revision = '4d452b8f4a16'
down_revision = 'e37bc10aebd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
