"""empty message

Revision ID: e37bc10aebd
Revises: 1fd7377c95c6
Create Date: 2015-07-19 14:24:23.341000

"""

# revision identifiers, used by Alembic.
revision = 'e37bc10aebd'
down_revision = '1fd7377c95c6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
